/interface:
  ros__parameters:
    # MEASURE
    # COM to Shoulder
    shoulder_length: 0.0435
    # Shoulder to Elbow
    elbow_length: 0.190
    # Elbow to Wrist
    wrist_length: 0.194
    # Forward Hip Separation
    hip_x: 0.470447   #0.455
    # Lateral Hip Separation
    hip_y: 0.197

    # ADJUSTABLE
    # Stance Length
    foot_x: 0.470447 # 0.455
    # Stance Width
    foot_y: 0.297
    # Stance Height
    height: 0.32 # 0.20
    # Adjust for balanced walk
    com_offset: -0.03

    # Time Step
    dt: 0.0125

    # Swing Period (lower is faster)
    Tswing: 0.22  # 0.2
    SwingPeriod_LIMITS: [0.1, 0.35]

    # Step Velocity (Using very low value as my main form of speed control is swing period)
    BaseStepVelocity: 0.25

    # Foot Clearance Height
    BaseClearanceHeight: 0.05  # 0.035
    ClearanceHeight_LIMITS: [0.0, 0.05]  # [0.0, 0.04]

    # Foot Penetration Depth
    BasePenetrationDepth: 0.003
    PenetrationDepth_LIMITS: [0.0, 0.02]
